config/routes.rb
ProjectMiscDefinitionx::Engine.routes.draw do
  resources :misc_definitions do
    collection do
      get :multi_csv
      get :multi_csv_result
    end
  end

end

app/models/project_misc_definitionx/misc_definition.rb
module ProjectMiscDefinitionx
  class MiscDefinition < ActiveRecord::Base
    attr_accessor :project_name
=begin
    attr_accessible :definition_category, :desp, :name, :project_id, :ranking_index, :definition_category, :project_name, 
                    :as => :role_new
    attr_accessible :definition_category, :desp, :name, :ranking_index, :definition_category, :project_name,
                    :as => :role_update
=end
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :project, :class_name => ProjectMiscDefinitionx.project_class.to_s
    
    validates :project_id, :presence => true, :numericality => {:only_integer => true, :greater_than => 0}
    validates :name, :presence => true,
                     :uniqueness => {:scope => [:project_id, :definition_category], :case_sensitive => false, :message => I18n.t('Duplicate Name!')} 
    validates :ranking_index, :numericality => {:only_integer => true, :greater_than => 0}, :if => 'ranking_index.present?'
    validates :definition_category, :presence => true   
    validate :dynamic_validate
      
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate_' + definition_category, 'project_misc_definitionx') if definition_category
      eval(wf) if wf.present?
    end   
    
    #role convert to csv
    def self.to_csv(project_id, definition_category, start_index=1, token = 'token')
      CSV.generate do |csv|
        #header = ['id', 'name', 'brief_note', 'last_updated_by_id', 'manager_role_id', 'created_at', 'updated_at', 'flag', 'fort_token', 'ranking_index']        
        all.each.with_index(start_index) do |base, i|
          #assembly array for the row
          row = Array.new
          row << i
          row << base.name
          row << base.desp
          row << base.last_updated_by_id
          row << nil #base.manager_role_id. 1 is for head of the company
          row << base.created_at
          row << base.updated_at
          row << '' #base.flag
          row << token 
          row << base.ranking_index
          #inject to csv
          csv << row
       
        end
      end
    end
    
    def self.m_to_csv(definitino_category, proj_ids, releases, tokens) #array
      c_i = 1
      CSV.generate do |csv|
        proj_ids.each do |v|
          i_a = v.split(',')
          prj_id = i_a[1].to_i # '0,25'
          rel = releases[i_a[0].to_i]
          token = tokens[i_a[0].to_i]
          records = MiscDefinition.where('resource_id = ? AND resource_string = ? AND release_id = ? AND definition_category = ?',  prj_id, ProjectMiscDefinitionx.project_class_string, rel, definition_category )
          
          records.each do |config|
            #assembly array for the row
            csv << make_row(config, c_i, token)
            c_i += 1
          end
        end
      end
    end
    
    def self.make_row(base, i, token)
      row = Array.new
      row << i
      row << base.name
      row << base.desp
      row << base.last_updated_by_id
      row << nil #base.manager_role_id. 1 is for head of the company
      row << base.created_at
      row << base.updated_at
      row << '' #base.flag
      row << token 
      row << base.ranking_index
      #inject to csv
      csv << row
      
      return row
    end

=begin    
    def self.position_to_csv(project_id, definition_category = 'position_definition', start_index=1, token = 'token')
      CSV.generate do |csv|
        #header = ['id', 'user_group_name', 'short_note', 'zone_id', 'group_type_id', manager+_group_id, 'created_at', 'updated_at', token]        
        all.each.with_index(start_index) do |base, i|
          #assembly array for the row
          row = Array.new
          row << i
          row << base.name
          row << base.desp
          row << 1 #hq, zone_id. 
          row << 1 #employee, group_type_id
          row << nil #general manager, manager group id
          row << base.created_at
          row << base.updated_at
          row << token 
          #inject to csv
          csv << row
       
        end
      end
    end  
=end
              
  end
end

app/controllers/project_misc_definitionx/application_controller.rb
module ProjectMiscDefinitionx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    #before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_action :page_params, :only => :index
    
    helper_method :return_misc_definitions
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination', session[:fort_token]).to_i
    end
    
  end
end

app/controllers/project_misc_definitionx/misc_definitions_controller.rb
require_dependency "project_misc_definitionx/application_controller"

module ProjectMiscDefinitionx
  class MiscDefinitionsController < ApplicationController
    before_action :require_employee
    before_action :load_record
    protect_from_forgery except: :edit  #for ajax new_log
    
    
    def index
      @title = t('Misc Definitions')
      @misc_definitions = params[:project_misc_definitionx_misc_definitions][:model_ar_r]
      @misc_definitions = @misc_definitions.where(definition_category: @definition_category) if @definition_category
      @misc_definitions = @misc_definitions.where(project_id: @project.id) if @project
      #@misc_definitions = @misc_definitions.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('misc_definition_index_view', 'project_misc_definitionx')
      #@erb_code = find_config_const('misc_definition_index_view_' + @definition_category, 'project_misc_definitionx')
      
      #for csv download
      respond_to do |format|
        format.html {@misc_definitions = @misc_definitions.page(params[:page]).per_page(@max_pagination) }
        format.csv do
          send_data @misc_definitions.to_csv(@project.id, @definition_category, params[:index_from].to_i, params[:token?]) #if @definition_category == 'role_definition'
          #send_data @misc_definitions.position_to_csv(@project.id, 'position_definition', params[:index_from].to_i, params[:token?]) if @definition_category == 'position_definition'
        end
      end
    end
  
    def new
      @title = t('New Misc Definition')
      @misc_definition = ProjectMiscDefinitionx::MiscDefinition.new()
      @erb_code = find_config_const('misc_definition_new_view', 'project_misc_definitionx')
    end
  
    def create
      @misc_definition = ProjectMiscDefinitionx::MiscDefinition.new(new_params)
      @misc_definition.last_updated_by_id = session[:user_id]
      if @misc_definition.save
        #redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
        redirect_to misc_definitions_path(:project_id => @misc_definition.project_id, :definition_category => @misc_definition.definition_category, :subaction => session[:subaction] ), 
                                                               :notice => t("Successfully Saved!") 
      else
        @project = ProjectMiscDefinitionx.project_class.find_by_id(params[:misc_definition][:project_id]) if params[:misc_definition][:project_id].present?
        @erb_code = find_config_const('misc_definition_new_view', 'project_misc_definitionx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Misc Definition')
      @misc_definition = ProjectMiscDefinitionx::MiscDefinition.find_by_id(params[:id])
      @erb_code = find_config_const('misc_definition_edit_view', 'project_misc_definitionx')
    end
  
    def update
      @misc_definition = ProjectMiscDefinitionx::MiscDefinition.find_by_id(params[:id])
      @misc_definition.last_updated_by_id = session[:user_id]
      if @misc_definition.update_attributes(edit_params)
        #redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
        redirect_to misc_definitions_path(:project_id => @misc_definition.project_id, :definition_category => @misc_definition.definition_category, :subaction => session[:subaction] ), 
                                                               :notice => t("Successfully Updated!") 
      else
        @erb_code = find_config_const('misc_definition_edit_view', 'project_misc_definitionx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
    
    def show
      @title = t('Misc Definition Info')
      @misc_definition = ProjectMiscDefinitionx::MiscDefinition.find_by_id(params[:id])
      @erb_code = find_config_const('misc_definition_show_view', 'project_misc_definitionx')
    end
  
    def destroy
      ProjectMiscDefinitionx::MiscDefinition.delete(params[:id].to_i)
      redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Deleted!")
    end
    
    def multi_csv
      @from_projects = ProojectMiscDefinitionx.project_class.where('cancelled = ? AND decommissioned = ?', false, false).order('id DESC')
      @erb_code = find_config_const('misc_definition_multi_csv_view', params[:controller].sub(/\/.+/, ''))
    end
    
    def multi_csv_result
      @misc_definitions = ProjectMiscDefinitionx::MiscDefinition.where('definition_category = ?', @definition_category).all
      respond_to do |format|
        format.csv do
          send_data @misc_definitions.m_to_csv(params[:ids], params[:release_ver], params[:pkg_code])
        end 
      end
    end
    
    protected
    def load_record
      @definition_category = params[:definition_category].strip if params[:definition_category].present?
      @definition_category = ProjectMiscDefinitionx::MiscDefinition.find_by_id(params[:id].to_i).definition_category.strip if params[:id].present?
      @project = ProjectMiscDefinitionx.project_class.find_by_id(params[:project_id]) if params[:project_id].present?
      @project = ProjectMiscDefinitionx.project_class.find_by_id(ProjectMiscDefinitionx::MiscDefinition.find_by_id(params[:id]).project_id) if params[:id].present?
    end
    
    private
    
    def new_params
      params.require(:misc_definition).permit(:definition_category, :desp, :name, :project_id, :ranking_index, :definition_category)
    end
    
    def edit_params
      params.require(:misc_definition).permit(:definition_category, :desp, :name, :ranking_index, :definition_category)
    end
 
  end
end

app/helpers/project_misc_definitionx/application_helper.rb
module ProjectMiscDefinitionx
  module ApplicationHelper
  end
end

app/helpers/project_misc_definitionx/misc_definitions_helper.rb
module ProjectMiscDefinitionx
  module MiscDefinitionsHelper
  end
end

app/views/project_misc_definitionx/misc_definitions/_form.html.erb
<% if  @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %> 
<h4><%=@title %></h4>
<%= simple_form_for @misc_definition do |f| %>     
  <%= f.input :name, :label => t('Name'), :readonly => readonly?(@misc_definition, 'name') %>
  <%= f.input :desp, :label => t("Description"), :input_html => {:rows => 2}, :readonly => readonly?(@misc_definition, 'desp') %> 
  <%= f.input :ranking_index, :label => t('Ranking Index'), :placehoder => '1, 2, 3 ...', :readonly => readonly?(@misc_definition, 'ranking_index') %> 
  
  <%= link_to t('Back'), misc_definitions_path(:definition_category => @definition_category, :subaction => @definition_category, :resource_id => @misc_definition.resource_id, :resource_string => @misc_definition.resource_string), :class => BUTTONS_CLS['action'] if has_action_right?('index_'+ @definition_category, params[:controller]) %>
  <%= link_to t('Back'), misc_definitions_path(:definition_category => @definition_category, :resource_id => @misc_definition.resource_id, :resource_string => @misc_definition.resource_string), :class => BUTTONS_CLS['action'] if has_action_right?('index', params[:controller]) %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %> 

<% end %>

app/views/project_misc_definitionx/misc_definitions/_form_list.html.erb
<% if  @erb_code %>
  <%= render inline: @erb_code, locals: {models: models} %>
  
<% else %>  
<div class="pagination"><%= will_paginate models %></div>
    <h4><%=@title + '-' + t(@definition_category.sub('_', ' ').pluralize.titleize) if @definition_cateogry.present? %></h4>
    <h4><%=@title if @definition_cateogry.blank? %></h4>
  <table class="table table-striped">
  	<p><%= form_tag misc_definitions_path(format: "csv"), method: :get do %>
           <div class="form-inputs">
	          <%= label_tag(:index_from, "Index From") %>
              <%= text_field_tag('index_from', '1', size: 6) %>
              <%= label_tag(:token, "Token ") %>
              <%= text_field_tag('token?', '', size: 12) %>
              <%= hidden_field_tag 'definition_category', @definition_category %>
              <%= hidden_field_tag 'subaction', @definition_category %>
                           
	         <%= submit_tag 'CSV' %>
	       </div>
      <% end if @project && (@definition_category == 'role_definition' || @definition_category == 'position_definition') %></p>
    <tr>
      <th><%= t('Create Date') %></th>
      <th><%= t('Name') %></th>
      <th><%= t('Description') %></th>
      <th><%= t('Ranking Index') %></th>
      <th><%= t('Last Updated By') %></th>
      <th></th>
    </tr>

    <% models.each do |r| %>
        <tr>
          <td><%= (r.created_at + 8.hours).strftime("%Y/%m/%d")%></td>
          <td><%= link_to r.name, SUBURI + "/view_handler?index=1&url=#{misc_definition_path(r, subaction: @definition_category)}" %></td>
          <td><%= r.desp %></td>
          <td><%= r.ranking_index %></td>
          <td><%= r.last_updated_by.name if r.last_updated_by_id.present? %></td>
          <td><%= link_to t('Edit'), edit_misc_definition_path(r, :subaction => @definition_category, definition_category: @definition_category, :format => :js), 
                  :remote => true, :class => BUTTONS_CLS['action'] if has_action_right?('update_' + @definition_category, params[:controller], r) %></td>
          <td><%= link_to t('Delete'), misc_definition_path(r, subaction: @definition_category), :method => :delete, :class => BUTTONS_CLS['danger'] if has_action_right?('destroy_' + @definition_category, params[:controller], r) %></td>
        </tr>
    <% end %>

  </table>

	<table class="table table-striped">
	  <tr>
	    <th>
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<%= link_to t("New " + @definition_category.titleize), new_misc_definition_path(:definition_category => @definition_category.strip, :subaction => @definition_category.strip, :resource_id => params[:resource_id], :resource_string => params[:resource_string], :format => :js), :remote => true, 
               :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create_' + @definition_category, params[:controller]) %> 
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<%= link_to t("New " + @definition_category.titleize), new_misc_definition_path(:definition_category => @definition_category.strip, :resource_id => params[:resource_id], :resource_string => params[:resource_string], :format => :js), :remote => true, 
               :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create', params[:controller]) %>   
		</th>
	  </tr>
	</table>

</div>
 
 <% end %> 

app/views/project_misc_definitionx/misc_definitions/_form_new.html.erb
<% if  @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h4><%=@title %></h4>
<%= simple_form_for(@misc_definition) do |f| %> 
  <%= f.input :name, :label => t('Name') %>
  <%= f.input :desp, :label => t("Description"), :input_html => {:rows => 2} %> 
  <%= f.input :definition_category, :input_html => {:value => @definition_category}, :as => :hidden %>
  <%= f.input :ranking_index, :label => t('Ranking Index'), :placehoder => '1, 2, 3 ...'%> 
  
  <%= link_to t('Back'), misc_definitions_path(:definition_category => @definition_category, :subaction => @definition_category, :resource_id => @misc_definition.resource_id, :resource_string => @misc_definition.resource_string), :class => BUTTONS_CLS['action'] if has_action_right?('index_'+ @definition_category, params[:controller]) %>
  <%= link_to t('Back'), misc_definitions_path(:definition_category => @definition_category, :resource_id => @misc_definition.resource_id, :resource_string => @misc_definition.resource_string), :class => BUTTONS_CLS['action'] if has_action_right?('index', params[:controller]) %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %> 

<% end %>

app/views/project_misc_definitionx/misc_definitions/create.html.erb
<h4>CategoryDefinitions#create</h4>
<p>Find me in app/views/customerx/category_definitions/create.html.erb</p>

app/views/project_misc_definitionx/misc_definitions/destroy.html.erb
<h1>MiscDefinitions#destroy</h1>
<p>Find me in app/views/project_misc_definitionx/misc_definitions/destroy.html.erb</p>

app/views/project_misc_definitionx/misc_definitions/edit.html.erb
 
<%= render 'form'  %>
 

  
 

app/views/project_misc_definitionx/misc_definitions/edit.js.erb
$("<%= escape_javascript render(:file => 'project_misc_definitionx/misc_definitions/edit.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();
$('#close').hide();

app/views/project_misc_definitionx/misc_definitions/index.html.erb
 
	<%= render partial: 'form_list', locals: {models: @misc_definitions} %>
 

app/views/project_misc_definitionx/misc_definitions/multi_csv.html.erb
<% if @erb_code %>
<%= render inline: @erb_code %>
<% else %>
<div class="container-fluid">
<p>Export Multiple <%=@definition_category.titlelize%> CSV</p>
 <%= form_tag multi_csv_result_misc_definitions_path(format: 'csv', definition_category: @defintion_category), :method => :get do %>
 <table class="table table-hover">
	<thead>
  <tr>
  	 <th></th>
     <th><%= t('Project Name') %></th>
     <th><%= t('Release') %></th>
     <th><%= t('Package#') %></th>
     <th><%= t('Create At') %></th>
     <th><%= t('Project Desp') %></th>
  </tr>
    </thead>
    <tbody>
	<% i = 0 %>
<% @from_projects.each do |r| %>
    <tr>
  	<% releases = OnboardDatax.project_misc_definition_class.where('definition_category = ? AND project_id = ?', 'release', r.id).order('id DESC')%>
  	<% pkg = ProjectMiscDefinitionx::MiscDefinition.where('definition_category = ? AND project_id = ?', 'package_code', r.id)%>
  	<% if releases.present? && pkg.present? %>
      <td><%= check_box_tag 'ids[]', i.to_s + ',' + r.id.to_s   %></td>
      <td><%= r.name %></td>
      <td><%= select_tag('release_ver[]', options_for_select(releases.select('id, name').map{|r| [r.name, r.id]})) %></td>
      <td><%= text_field_tag 'pkg_code[]', pkg.first.name if pkg.present? %></td>
      <td><%= r.created_at.strftime('%Y/%m/%d') %></td>
      <td><%= r.project_desp[0..60] if r.project_desp %></td>
	  <% i += 1 %>
    <% end %>
  </tr>
<% end %>
  </tbody>
    </table>
		
	<div class="btn-toolbar">
   
  		  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  		  <%= submit_tag t('Save') ,:name => "save", :class => BUTTONS_CLS['action'] %>
  	 
    </div>
 <% end %>

</div>
<% end %>

app/views/project_misc_definitionx/misc_definitions/multi_csv_result.html.erb
<%= render partial: 'form_list', locals: {models: @misc_definitions} %>

app/views/project_misc_definitionx/misc_definitions/new.html.erb
<%= render 'form_new' %>

app/views/project_misc_definitionx/misc_definitions/new.js.erb
$("<%= escape_javascript render(:file => 'project_misc_definitionx/misc_definitions/new.html.erb') %>").insertAfter('#new_log_link');
$('#new_log_link').hide();
$('#close').hide();
$('#btn1_link').hide();
$('#btn2_link').hide(); 
$('#btn3_link').hide(); 

app/views/project_misc_definitionx/misc_definitions/show.html.erb
<% if  @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<h4><%=@title %></h4>

<p>
  <b><%= t('Create Date') %></b>
  <%= @misc_definition.created_at.strftime("%Y/%m/%d") %>
</p>
<p>
  <b><%= t('Name') %></b>
  <%= @misc_definition.name %>
</p>
<p>
  <b><%= t('Description') %></b>
  <%= @misc_definition.desp %>
</p>
<p>
  <b><%= t('Ranking Index')  %></b>
  <%= @misc_definition.ranking_index %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @misc_definition.last_updated_by.name %>
</p>
   <table class="table table-striped">
	  <tr>
	    <th>
  	  	  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
  	  	  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  		  <%= link_to t('Delete'), misc_definition_path(@misc_definition, subaction: @misc_definition.definition_category), :method => :delete, :confirm => 'Delete the record?', :class => BUTTONS_CLS['action'] if has_action_right?('destroy_' + @misc_definition.definition_category, params[:controller], @misc_definition) %>
        </th>
	  </tr>
	</table>    	


<% end %>

app/views/project_misc_definitionx/misc_definitions/update.html.erb
<h4>CategoryDefinitions#update</h4>
<p>Find me in app/views/customerx/category_definitions/update.html.erb</p>